### ISSUE TITLE
[Anon] Infernal Dwarves: Infernal dwarfs Prophet is missing most of their equipment options

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/nr-t9a#17]
**Problem:**
Infernal dwarfs Prophet is missing most of their equipment options

**Expected:**
The equipment to be in the same location as all the other units

**List:** https://www.newrecruit.eu/app/list/CY8FY

**Comment by vflam** [comment]
Hello, this issue does not seem to be happening when I make a new list. It looks like something strange happened in your list. Could you create a new list and let me know if you manage to reproduce it?
