### ISSUE TITLE
[Anon] Warriors of the Dark Gods: Spells attached to exhalted herald are not the ones available

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/nr-t9a#21]
**Problem:**
Spells attached to exhalted herald are not the ones available

**Expected:**
Should appear the spells from Occultism (the same than the declared in de manisfetations)

**List:** https://www.newrecruit.eu/app/list/PdLhM

**Comment by dtamajon** [comment]
- Army Book: https://www.the-ninth-age.com/local/cache-gd2/2e/111392397d4922d9b99de0b1f2b9da.png?1606470877
- Edition: 3rd Edition, version Public Test - Hotfix 1
- Date: August 29, 2024

Expected spells:
Wrath of God (Thaumaturgy)
Hellfire (Hereditary Spell)
Hand of Glory (Occultism)
The Devouring Dark (Occultism)
Pentagram of Pain (Occultism)
The Grave Calls (Occultism)
Umbral Majesty (Occultism)
