### ISSUE TITLE
[Anon] Warriors of the Dark Gods: Favor rules of Chosen Lord are wrong

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/nr-t9a#22]
**Problem:**
Favor rules of Chosen Lord are wrong

**Expected:**
Apply the text of current Favours of the Dark Gods

**List:** https://www.newrecruit.eu/app/list/lv8Ja

**Comment by dtamajon** [comment]
- Army Book: https://www.the-ninth-age.com/local/cache-gd2/2e/111392397d4922d9b99de0b1f2b9da.png?1606470877
- Edition: 3rd Edition, version Public Test - Hotfix 1
- Date: August 29, 2024

**Favours of the Dark Gods**

**Envy**
Charge Range and Pursue Distance rolls by units containing this Favour are Maximised.

**Gluttony**
The first time a model with this Favour is on the winning side of a combat, its model parts with this FavourPath of the Favoured gain +1 Str with Duration: Permanent.

**Greed**
The model part with Path of the Favoured gains Great Weapon, Halberd, Paired Weapons, and Weapon Master. A Chosen Lord with this Favour may take a second item from either the Artefacts category or the Potions and Scrolls category (but cannot take a second item from both categories).

**Lust**
The model gains Feigned Flight.

**Pride**
Courage Tests taken by units containing this Favour are Minimised. Command Tests taken by units containing this Favour are Maximised.

**Sloth**
The model gains +1 Res. When the model’s unit declares a Charge or performs a March Move, the effect is lost until the start of the Melee Phase in the next Player Turn.

**Wrath**
The model part with Path of the Favoured gains Frenzy, Fury, and Unruly.
