### ISSUE TITLE
[Anon] Orcs and Goblins: It’s not allowing me to select an armor enchantment for the orc warlord

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/nr-t9a#26]
**Problem:**
It’s not allowing me to select an armor enchantment for the orc warlord

**Expected:**
To be able to select an armor enchantment

**List:** https://www.newrecruit.eu/app/list/zkdbA

**Comment by vflam** [comment]
Hello, I am not sure what happened to your list, perhaps it was created at a time where this was missing and it has been fixed since.

If you delete your Orc Warlord and make a new one, you should see enchants
