### ISSUE TITLE
[Anon] Ogre Khans: My list titled Mixed Arms is 3999pts but in the Lists screen it shows as only being 1950pts.

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/nr-t9a#30]
**Problem:**
My list titled Mixed Arms is 3999pts but in the Lists screen it shows as only being 1950pts.

**Expected:**
To show as 3999pts.

**List:** https://www.newrecruit.eu/app/list/FbvAy

**Comment by vflam** [comment]
Hello, I am unable to reproduce that.
Does it still show an incorrect total after a page refresh? What if you make a change to the list (like add/remove a unit), does it fix the total?

It would help if you were able to reproduce it from a new list.
