### ISSUE TITLE
[Anon] Highborn Elves: In 9th age its impossible to add secondary objectives

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/nr-t9a#38]
**Problem:**
In 9th age its impossible to add secondary objectives

**Expected:**
You should be able to do that in game assist

 **Additional Info:**
Android os

**List:** https://www.newrecruit.eu/app/list/LFQsG

**Comment by vflam** [comment]
it is possible if you make a new game and select Broken Iles as season
