### ISSUE TITLE
[Anon] Vermin Swarm: Pestilent purpit option 35 pts is unneccary 

### ISSUE THREAD

**Issue by NewRecruitAnon** [vflam/nr-t9a#63]
**Problem:**
Pestilent purpit option 35 pts is unneccary 

**Expected:**
I would like you to delete this 

 **Additional Info:**
It makes lists 35 pts more. There is a failure. Thanks

**List:** https://www.newrecruit.eu/app/list/0UhwK

**Comment by vflam** [comment]
not sure I understand that, pestilent pulpit is 35 pts and its mandatory for cult of errahman, nr seems correct
